export const GET_JURISDICTIONS = 'GET_JURISDICTIONS';
export const ADD_JURISDICTION = 'ADD_JURISDICTION';
export const DELETE_JURISDICTION = 'DELETE_JURISDICTION';
export const UPDATE_JURISDICTION = 'UPDATE_JURISDICTION';
export const JURISDICTION_ERROR = 'JURISDICTION_ERROR';
