export const GET_JURISDICTIONS = 'GET_JURISDICTIONS';
export const ADD_JURISDICTION = 'ADD_JURISDICTION';
export const DELETE_JURISDICTION = 'DELETE_JURISDICTION';
export const UPDATE_JURISDICTION = 'UPDATE_JURISDICTION';
export const JURISDICTION_ERROR = 'JURISDICTION_ERROR';
export const SET_DRAGGED_JURISDICTION = 'SET_DRAGGED_JURISDICTION';

// Allocated Day Types
export const GET_ALLOCATED_DAYS = 'GET_ALLOCATED_DAYS';
export const ADD_ALLOCATED_DAY = 'ADD_ALLOCATED_DAY';
export const ALLOCATED_DAY_ERROR = 'ALLOCATED_DAY_ERROR';
